import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Provider } from "@portfolio/components/ui/provider";

import "./globals.css";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Desenvolvedor Front-End - Vitor Batista",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.variable}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
